name: Python Application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Проверка исходного кода
        uses: actions/checkout@v2

      - name: Настройка Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install unittest

      - name: Запуск тестов
        run: |
          cd labOne
          python -m unittest test_lab.py

            
